[package]
name = "ayebear-1brc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
hashbrown = "0.14"
memmap2 = "0.9"
